### ISSUE TITLE
what is the ";" 

### ISSUE THREAD

**Issue by fusco** [david-becu/projetfallout#2]
https://github.com/david-becu/projetfallout/blob/1b9b07ac4006f9b9af41149e8f639bde673473dc/index.html#L19

On ne mets pas des ";" pour séparer les noms des class ou des id, mais de simple espace entre les noms.

**Comment by david-becu** [comment]
en effet, ce n'est pas nécessaire, au miieux ce petit détail est ignoré par le navigateur.
