### ISSUE TITLE
why use a h3 tag ?

### ISSUE THREAD

**Issue by fusco** [david-becu/projetfallout#6]
https://github.com/david-becu/projetfallout/blob/1b9b07ac4006f9b9af41149e8f639bde673473dc/index.html#L40

quel est l'intérêt d'utiliser une balise H3 ici ?

**Comment by david-becu** [comment]
il n'y a en effet aucun intérêt à utiliser une balise h3 à ce niveau, je ne me souviens pas pourquoi cet élément est à cette place.
